---
- hosts: all
  tasks:

# Set the hostname based on the inventory file : servername
# http://docs.ansible.com/ansible/latest/modules/hostname_module.html
  - name: Set the hostname
    hostname: 
     name: "{{ servername }}"

# We need the Epel repository to install nginx
  - name: Install epel release for nginx
    yum: 
     name: epel-release 
     state: present

# http://docs.ansible.com/ansible/latest/modules/yum_module.html
  - name: Install a list of packages - Redhat
    yum: name={{item}} state=present
    with_items:
       - epel-release
       - nginx
       - vim

# http://docs.ansible.com/ansible/latest/modules/service_module.html
  - name: Ensure nginx is set to start on boot
    service: 
     name: nginx 
     state: started 
     enabled: yes 

# http://docs.ansible.com/ansible/latest/modules/template_module.html
  - name: Send a custom index.html to the server
    template: 
     src: files/index.j2
     dest: /usr/share/nginx/html/index.html
     owner: nginx
     group: nginx
     backup: yes
